version: '3.5'

services:
  # Primary services
  app:
    build:
      context: .
    image: birky50/app
    container_name: birky50_app
    command: yarn start
    volumes:
      - .:/app:delegated
    ports:
      - 3000:3000
