// flow-typed signature: 87c09814bf4a0cb3fbf0c82f783c22e2
// flow-typed version: <<STUB>>/cli-error-notifier_v^2.0.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-error-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-error-notifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-error-notifier/cli' {
  declare module.exports: any;
}

declare module 'cli-error-notifier/lib/error-notifier' {
  declare module.exports: any;
}

declare module 'cli-error-notifier/lib/notifier-options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-error-notifier/cli.js' {
  declare module.exports: $Exports<'cli-error-notifier/cli'>;
}
declare module 'cli-error-notifier/lib/error-notifier.js' {
  declare module.exports: $Exports<'cli-error-notifier/lib/error-notifier'>;
}
declare module 'cli-error-notifier/lib/notifier-options.js' {
  declare module.exports: $Exports<'cli-error-notifier/lib/notifier-options'>;
}
