// flow-typed signature: 4bd130e367d6556a1d3d3e0f01dddaab
// flow-typed version: <<STUB>>/jest-puppeteer_v^3.1.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-puppeteer' {
  declare module.exports: any;
}
