// flow-typed signature: 02eab6af1b2386e564ed20846482f72b
// flow-typed version: <<STUB>>/jest-puppeteer_v^3.2.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-puppeteer' {
  declare module.exports: any;
}
