// flow-typed signature: 59326fb3acd5989535b77b035615389a
// flow-typed version: <<STUB>>/ntl_v^3.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ntl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ntl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ntl/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ntl/cli.js' {
  declare module.exports: $Exports<'ntl/cli'>;
}
