// flow-typed signature: 88babd1bc677c4ca7118c8dc5d2e76b8
// flow-typed version: <<STUB>>/react-app-rewire-babel-loader_v^0.1.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-babel-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-babel-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-app-rewire-babel-loader/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-app-rewire-babel-loader/dist/index' {
  declare module.exports: any;
}

declare module 'react-app-rewire-babel-loader/dist/index.umd' {
  declare module.exports: any;
}

declare module 'react-app-rewire-babel-loader/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-app-rewire-babel-loader/dist/index.es.js' {
  declare module.exports: $Exports<'react-app-rewire-babel-loader/dist/index.es'>;
}
declare module 'react-app-rewire-babel-loader/dist/index.js' {
  declare module.exports: $Exports<'react-app-rewire-babel-loader/dist/index'>;
}
declare module 'react-app-rewire-babel-loader/dist/index.umd.js' {
  declare module.exports: $Exports<'react-app-rewire-babel-loader/dist/index.umd'>;
}
declare module 'react-app-rewire-babel-loader/src/index.js' {
  declare module.exports: $Exports<'react-app-rewire-babel-loader/src/index'>;
}
