// flow-typed signature: b3990b529f19aca7a9a2cfe61be646fc
// flow-typed version: <<STUB>>/react-cosmos_v^4.5.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cosmos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cosmos' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cosmos/bin/cosmos-export' {
  declare module.exports: any;
}

declare module 'react-cosmos/bin/cosmos' {
  declare module.exports: any;
}

declare module 'react-cosmos/bin/print-fixture-files' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/client/loader-entry' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/client/mount' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/client/react-devtools-hook' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/client/react-error-overlay' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/client/user-modules' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/export' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/get-env' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/playground-html' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/print-fixture-files' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/server-web' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/server' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/webpack/attach-webpack' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/webpack/default-webpack-config' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/webpack/embed-modules-webpack-loader' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/webpack/extend-webpack-config' {
  declare module.exports: any;
}

declare module 'react-cosmos/dist/server/webpack/user-webpack-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cosmos/bin/cosmos-export.js' {
  declare module.exports: $Exports<'react-cosmos/bin/cosmos-export'>;
}
declare module 'react-cosmos/bin/cosmos.js' {
  declare module.exports: $Exports<'react-cosmos/bin/cosmos'>;
}
declare module 'react-cosmos/bin/print-fixture-files.js' {
  declare module.exports: $Exports<'react-cosmos/bin/print-fixture-files'>;
}
declare module 'react-cosmos/dist/client/loader-entry.js' {
  declare module.exports: $Exports<'react-cosmos/dist/client/loader-entry'>;
}
declare module 'react-cosmos/dist/client/mount.js' {
  declare module.exports: $Exports<'react-cosmos/dist/client/mount'>;
}
declare module 'react-cosmos/dist/client/react-devtools-hook.js' {
  declare module.exports: $Exports<'react-cosmos/dist/client/react-devtools-hook'>;
}
declare module 'react-cosmos/dist/client/react-error-overlay.js' {
  declare module.exports: $Exports<'react-cosmos/dist/client/react-error-overlay'>;
}
declare module 'react-cosmos/dist/client/user-modules.js' {
  declare module.exports: $Exports<'react-cosmos/dist/client/user-modules'>;
}
declare module 'react-cosmos/dist/server/export.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/export'>;
}
declare module 'react-cosmos/dist/server/get-env.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/get-env'>;
}
declare module 'react-cosmos/dist/server/playground-html.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/playground-html'>;
}
declare module 'react-cosmos/dist/server/print-fixture-files.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/print-fixture-files'>;
}
declare module 'react-cosmos/dist/server/server-web.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/server-web'>;
}
declare module 'react-cosmos/dist/server/server.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/server'>;
}
declare module 'react-cosmos/dist/server/webpack/attach-webpack.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/webpack/attach-webpack'>;
}
declare module 'react-cosmos/dist/server/webpack/default-webpack-config.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/webpack/default-webpack-config'>;
}
declare module 'react-cosmos/dist/server/webpack/embed-modules-webpack-loader.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/webpack/embed-modules-webpack-loader'>;
}
declare module 'react-cosmos/dist/server/webpack/extend-webpack-config.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/webpack/extend-webpack-config'>;
}
declare module 'react-cosmos/dist/server/webpack/user-webpack-config.js' {
  declare module.exports: $Exports<'react-cosmos/dist/server/webpack/user-webpack-config'>;
}
