// flow-typed signature: e0206f7288079d1249146c69e29a1312
// flow-typed version: <<STUB>>/react-perf-devtool_v^3.0.7/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-perf-devtool'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-perf-devtool' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-perf-devtool/lib/index' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/lib/npm/hook' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/lib/shared/commitChanges' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/lib/shared/generate' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/lib/shared/hostEffects' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/lib/shared/lifecycle' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/lib/shared/math' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/lib/shared/parse' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/lib/shared/parseMeasures' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/lib/shared/totalTime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-perf-devtool/index' {
  declare module.exports: $Exports<'react-perf-devtool'>;
}
declare module 'react-perf-devtool/index.js' {
  declare module.exports: $Exports<'react-perf-devtool'>;
}
declare module 'react-perf-devtool/lib/index.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/index'>;
}
declare module 'react-perf-devtool/lib/npm/hook.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/npm/hook'>;
}
declare module 'react-perf-devtool/lib/shared/commitChanges.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/shared/commitChanges'>;
}
declare module 'react-perf-devtool/lib/shared/generate.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/shared/generate'>;
}
declare module 'react-perf-devtool/lib/shared/hostEffects.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/shared/hostEffects'>;
}
declare module 'react-perf-devtool/lib/shared/lifecycle.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/shared/lifecycle'>;
}
declare module 'react-perf-devtool/lib/shared/math.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/shared/math'>;
}
declare module 'react-perf-devtool/lib/shared/parse.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/shared/parse'>;
}
declare module 'react-perf-devtool/lib/shared/parseMeasures.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/shared/parseMeasures'>;
}
declare module 'react-perf-devtool/lib/shared/totalTime.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/shared/totalTime'>;
}
