// flow-typed signature: 00c8103494fdb8fd556b91cb41fe48a7
// flow-typed version: <<STUB>>/react-cosmos-flow_v^4.6.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cosmos-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cosmos-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cosmos-flow/config' {
  declare module.exports: any;
}

declare module 'react-cosmos-flow/context' {
  declare module.exports: any;
}

declare module 'react-cosmos-flow/fixture' {
  declare module.exports: any;
}

declare module 'react-cosmos-flow/jest' {
  declare module.exports: any;
}

declare module 'react-cosmos-flow/loader' {
  declare module.exports: any;
}

declare module 'react-cosmos-flow/module' {
  declare module.exports: any;
}

declare module 'react-cosmos-flow/playground' {
  declare module.exports: any;
}

declare module 'react-cosmos-flow/proxy' {
  declare module.exports: any;
}

declare module 'react-cosmos-flow/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cosmos-flow/config.js' {
  declare module.exports: $Exports<'react-cosmos-flow/config'>;
}
declare module 'react-cosmos-flow/context.js' {
  declare module.exports: $Exports<'react-cosmos-flow/context'>;
}
declare module 'react-cosmos-flow/fixture.js' {
  declare module.exports: $Exports<'react-cosmos-flow/fixture'>;
}
declare module 'react-cosmos-flow/jest.js' {
  declare module.exports: $Exports<'react-cosmos-flow/jest'>;
}
declare module 'react-cosmos-flow/loader.js' {
  declare module.exports: $Exports<'react-cosmos-flow/loader'>;
}
declare module 'react-cosmos-flow/module.js' {
  declare module.exports: $Exports<'react-cosmos-flow/module'>;
}
declare module 'react-cosmos-flow/playground.js' {
  declare module.exports: $Exports<'react-cosmos-flow/playground'>;
}
declare module 'react-cosmos-flow/proxy.js' {
  declare module.exports: $Exports<'react-cosmos-flow/proxy'>;
}
declare module 'react-cosmos-flow/react.js' {
  declare module.exports: $Exports<'react-cosmos-flow/react'>;
}
